### ISSUE TITLE
testing tessagon in blender 2.8

### ISSUE THREAD

**Issue by onelsonic** [cwant/tessagon#15]
Hi there,
I tried to run the tessagon python script in the last blender 2.8, and it is giving me errors.
Also can we tessellate a 3D object with this script?

**Comment by cwant** [comment]
Thanks for the report!

I hope to test the script on Blender 2.8 sometime in the next month or so (after relearning everything I know about Blender -- 2.8 is quite the re-write!).

This script will not tessellate an arbitrary 3D object -- check out "Tissue" for that sort of use. This script works on rectangles, so in theory it could tessellate meshes that only have quad faces in them, but I haven't gotten around to making that work yet. I also have been working on some code to tessellate surfaces of revolution (i.e,, start with a curve and an axis of revolution to generate a surface), but that code isn't ready for prime time yet.

**Comment by cwant** [comment]
Hi there, this works with Blender 2.8 now.

**Comment by onelsonic** [comment]
nice @cwant !!
