### ISSUE TITLE
Tesselation on Meshes?

### ISSUE THREAD

**Issue by Tungee** [cwant/tessagon#7]
Hi its not a bug, but a question cwant:
Could this also be used to tessagon also a mesh?
Best regards

**Comment by cwant** [comment]
Hi Tungee,

Currently no. I have a project that is working on it (`blender_to_math`, which will convert blender objects into math formulas that tessagon can read), but it's not fit for human consumption yet. It will initially handle surfaces of revolution (take a Blender profile mesh/curve and an axis, and output a function that wraps the curve around an axis), which is how I created the colorful objects in this photo:

![](https://www.shapeways.com/forum/attachments/20171221_193834-jpg.247103/)

The problem of re-tessellating an arbitrary Blender mesh is much harder and will need some deeper thought (e.g., Tessagon works on quad-shaped tiles internally, but blender meshes can have faces that are triangles, pentagons, etc.)

**Comment by Tungee** [comment]
Hi Cwant sorry for the late reply;
didnt noticed your answer.
What do you mean, an mesh object to Math formula?
That would be insane!

Would this  function for example?:
![bildschirmfoto 2018-03-29 um 17 21 34](https://user-images.githubusercontent.com/3286171/38097372-b666a958-3364-11e8-8363-a80732713955.png)

 I want to reshape the surface with equal size length faces
In blender i get this with irregular density
![bildschirmfoto 2018-03-29 um 17 21 45](https://user-images.githubusercontent.com/3286171/38097371-b6440592-3364-11e8-899c-51094cc2fa56.png)

Best Regards

**Comment by cwant** [comment]
Hi @Tungee, sorry for the slow response. Probably what I have planned wouldn't work with that sort of thing.
